Add proper error handler to git-release script

diff --git a/plugins/git/bin/git-release b/plugins/git/bin/git-release
--- a/plugins/git/bin/git-release
+++ b/plugins/git/bin/git-release
@@ -1,9 +1,32 @@
-#!/bin/sh
-set -e
+#!/usr/bin/env bash
+
+## Git release
+##
+## My own git flow helper.
+##
+## Usage: git release <start/finish/list> [args]
+##
+## Subcommands:
+##   start          Creates a new release branch
+##   finish         Merges the current branch into master and creates a tag
+##   list           List all releases
+##
+
+# Error handler
+trap error_handler ERR
+
+function error_handler {
+  EXIT_CODE=$?
+
+  echo
+  echo "An error has occurred!"
+  echo "Exit code: ${EXIT_CODE}"
+  exit 1
+}
 
 function help {
   echo "usage:"
-  echo ""
+  echo
   echo "  git release start [name]   creates a new release branch."
   echo "                             if name is not specified, then it'll be vYY.M.S as in v16.1.1"
   echo "  git release finish [name]  merges the current release into master branch and creates a new tag"
@@ -75,7 +98,7 @@ if [[ $COMMAND != "" ]]; then
           # Fine, now create the release branch
           git checkout -B release/$NEW_VERSION master
 
-          echo ""
+          echo
           echo "Merge work on it and then finish it by doing:"
           echo "  git release finish"
           ;;
@@ -109,21 +132,23 @@ if [[ $COMMAND != "" ]]; then
           # Generate a tag from master
           git tag --sign $RELEASE_NAME
 
-          # Delete release branch (both locally and remotely)
+          # Delete release branch locally
           git branch -d $RELEASE_BRANCH
-          if [[ $(git ls-remote --heads origin $RELEASE_BRANCH) != "" ]]; then
-            git push origin --delete $RELEASE_BRANCH
-          fi
 
-          # Send both master and new tag to all remotes
           for r in $(git remote); do
+            # Delete release branch remotely
+            if [[ $(git ls-remote --heads $r $RELEASE_BRANCH) != "" ]]; then
+              git push $r --delete $RELEASE_BRANCH || true
+            fi
+
+            # Send both master and new tag to all remotes
             git push $r master
-            git push $r $RELEASE_NAME
+            git push $r $RELEASE_BRANCH
           done
 
           # Create the release draft
-          # hub release create -dF - -c "$(git rev-parse HEAD)" "$version_tag" || true
-          # hub browse -- "releases/${version_tag}"
+          # hub release create -dF - -c "$(git rev-parse HEAD)" "Release $RELEASE_NAME" || true
+          # hub browse -- "${RELEASE_NAME}"
           ;;
 
         list)
@@ -133,9 +158,9 @@ if [[ $COMMAND != "" ]]; then
 
           printf "    ${COLOR_LIGHT_GREEN}Released (tags):$COLOR_NC\n"
           git tag -l "v*" | version_sort | column
-          echo ""
+          echo
           printf "    ${COLOR_LIGHT_RED}Unreleased (branches):$COLOR_NC\n"
-          git branch --list | \grep -E --only-matching 'release/.*' | version_sort |  column
+          git branch --list | \grep -E --only-matching 'release/.*' | version_sort | column
           ;;
 
         help)
@@ -144,7 +169,7 @@ if [[ $COMMAND != "" ]]; then
 
         *)
           echo "'$COMMAND' is not a valid command"
-          echo ""
+          echo
           help
           ;;
     esac
