refactor(all): add support for a second computer setup

diff --git a/modules/borgmatic/bin/borgmatic b/modules/borgmatic/bin/borgmatic
--- a/modules/borgmatic/bin/borgmatic
+++ b/modules/borgmatic/bin/borgmatic
@@ -1,45 +1,26 @@
 #!/usr/bin/env bash
 # vim: noexpandtab tabstop=2
 #
-# This is a wrapper around borgmatic so that the `list` subcommand also executes hooks, as well as
-# adds automatically the --config option if not specified and the config file is not located at the
-# default location (/etc/borgmatic/config.yaml /etc/borgmatic.d $HOME/.config/borgmatic/config.yaml
-# $HOME/.config/borgmatic.d)
+# This is a wrapper around borgmatic so that the `list` subcommand also executes hooks.
 
 main() {
 	# Set HOME to whoever is invoking sudo, or in case this varibale isn't set, just set it to ~
 	eval HOME=~$SUDO_USER
 
 	# Finds out where borgmatic config file is
-	borgmatic_file_path="$(get_borgmatic_cfg_path)"
-
-	# Then gets whether the config is specified in opts
-	get_config_opt "$@"; config_is_specified=$?
-
 	if is_list_cmd "$@"; then
-		run_list "$@"
+		run_hooks before
+		borgmatic "$@"; status=$?
+		run_hooks after
+
+		return $status
 	else
-		borgmatic --config "$config_path" "$@"
+		borgmatic "$@"
 	fi
-}
-
-get_config_opt() {
-	while [ $# -gt 0 ]; do
-		case "$1" in
-			--config|-c) return 1 ;;
-			*) shift ;;
-		esac
-	done
-
-	return 0
 }
 
 borgmatic() {
-	if [ $config_is_specified == 1 ]; then
-		/usr/bin/borgmatic "$@"
-	else
-		/usr/bin/borgmatic --config "$borgmatic_file_path" "$@"
-	fi
+	/usr/bin/borgmatic "$@"
 }
 
 is_list_cmd() {
@@ -50,32 +31,16 @@ is_list_cmd() {
 	[ "$cmd" = "list" ] || [ "$cmd" = "--list" ] || [ "$cmd" == "-l" ]
 }
 
-get_borgmatic_cfg_path() {
-	local ansible_config user_name borgmatic_config
-
-	ansible_config="$HOME/.dotfiles/ansible/roles/desktop-tools/defaults/main.yml"
-	user_name=$(yq -r ".user_name" "$ansible_config")
-	borgmatic_config=$(yq -r ".borgmatic_config" "$ansible_config")
-	sed "s/{{ user_name }}/$user_name/" <<< "$borgmatic_config"
-}
-
 run_hooks() {
 	local type=$1
+	local config_path="$HOME/.config/borgmatic/config.yaml"
 
 	while read -r hook; do
 		eval "$hook" || {
-			echo "Failure while running ${type}_everything hook on '$borgmatic_file_path'"
+			echo "Failure while running ${type}_everything hook on '$config_path'"
 			exit 1
 		}
-	done < <(yq -r ".hooks.${type}_everything[]" "$borgmatic_file_path")
-}
-
-run_list() {
-	run_hooks before
-	borgmatic "$@"; status=$?
-	run_hooks after
-
-	return $status
+	done < <(yq -r ".hooks.${type}_everything[]" "$config_path")
 }
 
 main "$@"
